/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ListComponent {
        "list": Array<object>;
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ParentComponent {
        "list": Array<object>;
        "name": string;
        "oldValue": string;
        "value": string;
    }
    interface UserComponent {
        "value": string;
    }
}
declare global {
    interface HTMLListComponentElement extends Components.ListComponent, HTMLStencilElement {
    }
    var HTMLListComponentElement: {
        prototype: HTMLListComponentElement;
        new (): HTMLListComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {
    }
    var HTMLParentComponentElement: {
        prototype: HTMLParentComponentElement;
        new (): HTMLParentComponentElement;
    };
    interface HTMLUserComponentElement extends Components.UserComponent, HTMLStencilElement {
    }
    var HTMLUserComponentElement: {
        prototype: HTMLUserComponentElement;
        new (): HTMLUserComponentElement;
    };
    interface HTMLElementTagNameMap {
        "list-component": HTMLListComponentElement;
        "my-component": HTMLMyComponentElement;
        "parent-component": HTMLParentComponentElement;
        "user-component": HTMLUserComponentElement;
    }
}
declare namespace LocalJSX {
    interface ListComponent {
        "list"?: Array<object>;
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParentComponent {
        "list"?: Array<object>;
        "name"?: string;
        "oldValue"?: string;
        "value"?: string;
    }
    interface UserComponent {
        "onUserNameEntered"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "list-component": ListComponent;
        "my-component": MyComponent;
        "parent-component": ParentComponent;
        "user-component": UserComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "list-component": LocalJSX.ListComponent & JSXBase.HTMLAttributes<HTMLListComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "parent-component": LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
            "user-component": LocalJSX.UserComponent & JSXBase.HTMLAttributes<HTMLUserComponentElement>;
        }
    }
}
